apiVersion: v2
name: tembo
version: 25.3.3
appVersion: 1.0.0
description: Helm chart to deploy the Tembo Platform
keywords:
  - tembo
dependencies:
  - name: cert-manager
    version: 1.14.4
    condition: global.certManagerEnabled
  - name: tembo
    condition: global.temboEnabled
    version: 25.3.3
  - name: monitoring
    condition: global.monitoringEnabled
    version: 25.3.3
  - name: traefik
    condition: global.traefikEnabled
    version: 25.3.3
