global:
  temboEnabled: true
  monitoringEnabled: false
  conductorEnabled: false
  traefikEnabled: true
  baseDomain: ~
tembo:
  conductor:
    env:
      - name: PG_CONN_URL
        valueFrom:
          secretKeyRef:
            name: control-plane-connection
            key: rw_uri
      - name: POSTGRES_QUEUE_CONNECTION
        valueFrom:
          secretKeyRef:
            name: control-plane-queue-connection
            key: rw_uri
      - name: CONTROL_PLANE_EVENTS_QUEUE
        value: "control_plane_aws_data_1_use1"
      - name: DATA_PLANE_EVENTS_QUEUE
        value: "conductor_aws_data_1_use1"
      - name: DATA_PLANE_BASEDOMAIN
        value: ~
      - name: BACKUP_ARCHIVE_BUCKET
        value: "tembo-backups"
      - name: CF_TEMPLATE_BUCKET
        value: "tembo-cf-templates"
      - name: METRICS_EVENTS_QUEUE
        value: "metrics_aws_data_1_use1"
      - name: IS_CLOUD_FORMATION
        value: "false"
      - name: STORAGE_ARCHIVE_BUCKET
        value: "tembo-storage"
      - name: PROMETHEUS_URL
        value: "http://tembo-kube-prometheus-stac-prometheus.tembo.svc.cluster.local:9090"
  tembo-operator:
    controller:
      monitoring:
        prometheusRule:
          enabled: true
        podMonitor:
          enabled: true
          port: http
          path: /metrics
      extraEnv:
        - name: DATA_PLANE_BASEDOMAIN
          value: ~
    cloudnative-pg:
      monitoring:
        podMonitorEnabled: true
  cpWebserver:
    env:
      - name: CLERK_SECRET_KEY
        value: ~
      - name: CLERK_WEBHOOK_SIGNING_SECRET
        value: ~
      - name: STRIPE_SECRET_KEY
        value: ~
      - name: STRIPE_WEBHOOK_SIGNING_SECRET
        value: ~
      - name: METRONOME_SECRET_KEY
        value: ~
monitoring:
  kube-prometheus-stack:
    alertmanager:
      alertmanagerSpec:
        image:
          tag: "v0.25.1"
    grafana:
      image:
        tag: "10.2.3"
    kube-state-metrics:
      metricLabelsAllowlist:
        - namespaces=[tembo.io/organization_id,tembo.io/instance_id]
      metricAnnotationsAllowList:
        - namespaces=[tembo.io/organization_id,tembo.io/instance_id]
        - pods=[tembo.io/organization_id,tembo.io/instance_id]
    prometheus:
      prometheusSpec:
        resources:
          limits:
            memory: 10Gi
          requests:
            memory: 5Gi
  promtail:
    config:
      snippets:
        extraRelabelConfigs:
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_annotation_tembo_io_organization_id
            target_label: tembo_organization_id
          - action: replace
            source_labels:
              - __meta_kubernetes_pod_annotation_tembo_io_instance_id
            target_label: tembo_instance_id
        pipelineStages:
          - cri: { }
          - match:
              selector: '{tembo_organization_id=~".+"}'
              stages:
                - labelallow:
                    - tembo_instance_id
                    - tembo_organization_id
                    - container
                    - stream
                    - app
                    - pod
                - tenant:
                    label: tembo_organization_id
          - output:
              source: message
