apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dataplaneWebserver.fullname" . }}
  labels:
    {{- include "dataplaneWebserver.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.dataplaneWebserver.replicas }}
  selector:
    matchLabels:
      {{- include "dataplaneWebserver.selectorLabels" . | nindent 6 }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      {{- with .Values.dataplaneWebserver.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dataplaneWebserver.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.dataplaneWebserver.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "dataplaneWebserver.fullname" . }}
      securityContext:
        {{- toYaml .Values.dataplaneWebserver.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          command:
          - /usr/local/bin/dataplane_webserver
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
          - name: RUST_LOG
            value: {{ .Values.dataplaneWebserver.logLevel }}
          - name: PROMETHEUS_URL
            value: {{ include "dataplaneWebserver.prometheusUrl" . }}
          {{- if .Values.dataplaneWebserver.env }}{{ .Values.dataplaneWebserver.env | default list | toYaml | nindent 10 }}{{- end }}
          securityContext:
            {{- toYaml .Values.dataplaneWebserver.securityContext | nindent 12 }}
          image: "{{ .Values.dataplaneWebserver.image.repository }}:{{ .Values.dataplaneWebserver.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.dataplaneWebserver.image.pullPolicy }}
          livenessProbe:
            httpGet:
              path: "/health/lively"
              port: http
          readinessProbe:
            httpGet:
              path: "/health/lively"
              port: http
          resources:
            {{- toYaml .Values.dataplaneWebserver.resources | nindent 12 }}
      {{- with .Values.dataplaneWebserver.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dataplaneWebserver.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dataplaneWebserver.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
