{{- if .Values.jobs.customS3Backup.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: custom-s3-creds
type: Opaque
data:
  ACCESS_KEY_ID: {{ .Values.jobs.customS3Backup.accessKeyId }}
  SECRET_ACCESS_KEY: {{ .Values.jobs.customS3Backup.secretAccessKey }}
{{- end }}
