apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: monitoring-cors-monitoring
  namespace: {{ .Values.jobs.lokiConfig.namespace }}
spec:
  headers:
    accessControlAllowHeaders:
      - Origin
      - Content-Type
      - Accept
      - Authorization
      - X-Scope-OrgID
      - X-Tembo-Org
      - X-Tembo-Instance
    accessControlAllowMethods:
      - GET
      - OPTIONS
    accessControlAllowOriginListRegex:
      {{- range .Values.jobs.lokiConfig.accessControlAllowOrigin }}
      -  {{ . }}
      {{- end }}
