traefik:
  additionalArguments:
    - "--entryPoints.ferretdb.address=:27018/tcp"
    - "--entryPoints.postgresql.address=:5432/tcp"
    # Require authentication for all HTTPS requests
    - "--entrypoints.websecure.http.middlewares=traefik-forwardauth@kubernetescrd"
    # Redirect from HTTP to HTTPS for all requests to HTTP port
#    - "--entrypoints.web.http.middlewares=traefik-https-redirect@kubernetescrd"
    # Configure min TLS version
    - "--entrypoints.websecure.http.tls.options=traefik-default@kubernetescrd"
    - "--providers.file.filename=/config/postgres-catchall.yaml"
    - "--log.format=json"
    - "--log.nocolor=true"
  volumes:
    - name: "postgres-catchall"
      mountPath: "/config"
      type: configMap
  ports:
    ferretdb:
      expose:
        default: true
      port: 27018
      exposedPort: 27018
      protocol: TCP
    postgresql:
      expose:
        default: true
      port: 5432
      exposedPort: 5432
      protocol: TCP
  deployment:
    # These configurations allow for the NLB to drain connections
    # An NLB can take up to 180 seconds to stop routing TCP connections
    # to a target.
    terminationGracePeriodSeconds: 200
    lifecycle:
      preStop:
        exec:
          command: ["/bin/sh", "-c", "sleep 180"]
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 5
