{{ if .Values.certificate.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-certificate
  namespace: {{ .Release.namespace }}
spec:
  secretName: traefik-cert
  duration: 2160h # 90d
  renewBefore: 720h # 30d
  subject:
    organizations:
      - {{ .Values.certificate.organization }}
  commonName: {{ .Values.certificate.commonName }}
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  dnsNames:
    - {{ .Values.certificate.commonName }}
{{ toYaml .Values.certificate.subjectAltNames | indent 4 }}
  issuerRef:
    name: {{ .Values.certificate.issuer.name }}
    kind: {{ .Values.certificate.issuer.kind }}
    group: cert-manager.io
{{ end }}
