apiVersion: v2
name: tembo
version: 24.2.0
description: A Helm chart to deploy the Tembo platform
keywords:
  - tembo
dependencies:
    - name: tembo-operator
      version: 0.7.1
      repository: https://tembo-io.github.io/tembo
    - name: conductor
      version: 0.5.2
      condition: global.conductorEnabled
      repository: https://tembo-io.github.io/tembo
