apiVersion: v2
name: tembo
version: 24.3.1
description: A Helm chart to deploy the Tembo platform
keywords:
  - tembo
dependencies:
    - name: tembo-operator
      version: 0.7.2
      repository: https://tembo-io.github.io/tembo
    - name: conductor
      version: 0.6.0
      repository: https://tembo-io.github.io/tembo
