apiVersion: v2
name: tembo
version: 25.3.4
description: A Helm chart to deploy the Tembo platform
keywords:
  - tembo
dependencies:
    - name: tembo-operator
      version: 0.9.1
      repository: https://tembo-io.github.io/tembo
    - name: conductor
      version: 0.7.1
      repository: https://tembo-io.github.io/tembo
    - name: traefik-https
      version: 0.0.1
    - name: cert-manager-issuer
      version: 0.1.0
