apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cpWebserver.fullname" . }}-affinity
  labels:
    {{- include "cpWebserver.labels" . | nindent 4 }}
data:
  affinity.json: |
    {{ .Values.postgresPodScheduling.affinity | toJson }}
  node-selector.json: |
    {{ .Values.postgresPodScheduling.nodeSelector | toJson }}
  tolerations.json: |
    {{ .Values.postgresPodScheduling.tolerations | toJson }}
